server:
  port: 8091

spring:
  flyway:
    enabled: false

syncmgmt:
  tier: leaf
  zone: zone-a
  subzone: _
  nodeId: leaf-za-1
  natsUrl: nats://127.0.0.1:4231

  bootstrap:
    enabled: false

  relay:
    enabled: false

  outbox:
    enabled: true
    max-retries: 0

  poc-admin:
    enabled: false
