server:
  port: 8092

spring:
  flyway:
    enabled: false

syncmgmt:
  tier: leaf
  zone: zone-b
  subzone: _
  nodeId: leaf-zb-1
  natsUrl: nats://127.0.0.1:4232

  bootstrap:
    enabled: false

  relay:
    enabled: false

  outbox:
    enabled: true
    max-retries: 0

  poc-admin:
    enabled: false
